//! `nextrs realtime generate` / `nextrs realtime deploy` — the Cloudflare
//! relay for `nextrs::realtime` on serverless deployments.
//!
//! The worker source ships inside the framework crate
//! (`nextrs::realtime_relay::WORKER_JS`) so its ticket HMAC can't drift from
//! the Rust signer; this module only writes it next to a `wrangler.toml` and,
//! for `deploy`, runs wrangler and sets the shared secret.

use std::path::Path;

use crate::cron::{self, COMPATIBILITY_DATE};

/// Where the relay is generated, beside the cron worker.
pub const OUTPUT_DIR: &str = ".nextrs/cloudflare/realtime";

pub fn generate(root: &Path) -> Result<String, String> {
    let config = cron::load_config(root)?;
    let out_dir = root.join(OUTPUT_DIR);
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("{}: {e}", out_dir.display()))?;
    cron::write(&out_dir.join("worker.js"), nextrs::realtime_relay::WORKER_JS)?;
    cron::write(&out_dir.join("wrangler.toml"), &wrangler_toml(&config.app.name))?;
    Ok(format!("{OUTPUT_DIR}: realtime relay `{}`", worker_name(&config.app.name)))
}

fn worker_name(app: &str) -> String {
    format!("{app}-realtime")
}

fn wrangler_toml(app: &str) -> String {
    format!(
        r#"# Generated by `nextrs realtime generate` — do not edit.
# The relay for nextrs::realtime: one Durable Object per topic.
name = "{name}"
main = "worker.js"
compatibility_date = "{COMPATIBILITY_DATE}"

[[durable_objects.bindings]]
name = "TOPICS"
class_name = "Topic"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Topic"]
"#,
        name = worker_name(app)
    )
}

/// Generate, `wrangler deploy`, then set NEXTRS_REALTIME_SECRET on the worker.
pub fn deploy(root: &Path) -> Result<(), String> {
    let summary = generate(root)?;
    eprintln!("nextrs: generated {summary}");
    let config = cron::load_config(root)?;
    let cwd = std::env::current_dir().map_err(|e| e.to_string())?;
    let report = crate::env_file::load(root, Some(&cwd), crate::env_file::Target::Production, config.deploy.as_ref())?;
    let secret = std::env::var("NEXTRS_REALTIME_SECRET").ok().filter(|s| s.len() >= 16).ok_or_else(|| {
        format!(
            "NEXTRS_REALTIME_SECRET (16+ characters) is required — the app signs tickets and publishes with it{}",
            report.describe_missing("NEXTRS_REALTIME_SECRET")
        )
    })?;
    let wrangler_config = std::fs::canonicalize(root.join(OUTPUT_DIR).join("wrangler.toml"))
        .map_err(|e| format!("{OUTPUT_DIR}/wrangler.toml: {e}"))?;
    cron::run_wrangler(root, &wrangler_config, &["deploy"], None)?;
    cron::run_wrangler(root, &wrangler_config, &["secret", "put", "NEXTRS_REALTIME_SECRET"], Some(&secret))?;
    eprintln!(
        "nextrs: relay deployed. Point the app at it (same secret on both sides):\n\n  \
         NEXTRS_REALTIME_URL=https://{}.<your-subdomain>.workers.dev\n  \
         NEXTRS_REALTIME_SECRET=<the value above>",
        worker_name(&config.app.name)
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_worker_and_config() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("nextrs.toml"),
            "[app]\nname = \"todos\"\nurl = \"https://todos.example\"\n\n[vercel]\nregions = [\"pdx1\"]\n",
        )
        .unwrap();
        generate(dir.path()).unwrap();
        let out = dir.path().join(OUTPUT_DIR);
        let worker = std::fs::read_to_string(out.join("worker.js")).unwrap();
        assert!(worker.contains("export class Topic extends DurableObject"));
        let toml = std::fs::read_to_string(out.join("wrangler.toml")).unwrap();
        assert!(toml.contains("name = \"todos-realtime\""));
        assert!(toml.contains("new_sqlite_classes = [\"Topic\"]"));
    }
}
