use askama::Template;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
// Defines `DocMeta` and `DOCS`, ordered by section then order.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_manifest.rs"));

struct Section {
    name: &'static str,
    items: Vec<&'static DocMeta>,
}

#[derive(Template)]
#[template(path = "docs/layout.html")]
struct DocsLayout<'a> {
    children: &'a str,
    sections: Vec<Section>,
}

fn sections() -> Vec<Section> {
    let mut sections: Vec<Section> = Vec::new();
    for doc in DOCS {
        match sections.last_mut() {
            Some(s) if s.name == doc.section => s.items.push(doc),
            _ => sections.push(Section {
                name: doc.section,
                items: vec![doc],
            }),
        }
    }
    sections
}

pub fn render(children: &str) -> String {
    DocsLayout {
        children,
        sections: sections(),
    }
    .render()
    .unwrap()
}
