//! Docs section layout (sidebar + content + TOC rail), as RSX.
//! Ported from the former Askama `docs/layout.html`.

use nextrs::rsx;
use nextrs::rsx::Rsx;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
// Defines `DocMeta` and `DOCS`, ordered by section then order.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_manifest.rs"));

struct Section {
    name: &'static str,
    items: Vec<&'static DocMeta>,
}

fn sections() -> Vec<Section> {
    let mut sections: Vec<Section> = Vec::new();
    for doc in DOCS {
        match sections.last_mut() {
            Some(s) if s.name == doc.section => s.items.push(doc),
            _ => sections.push(Section {
                name: doc.section,
                items: vec![doc],
            }),
        }
    }
    sections
}

// Layouts only receive child HTML, so active state + the "On this page" TOC
// are resolved client-side from the rendered content. Raw: script bodies must
// not be HTML-escaped.
const TOC_SCRIPT: &str = r##"<script>
  // Layouts only receive child HTML, so active state + the "On this page" TOC
  // are resolved client-side from the rendered content.
  (function () {
    var path = location.pathname.replace(/\/+$/, "");
    document.querySelectorAll(".docs-sidebar a").forEach(function (a) {
      if (a.getAttribute("href") === path) a.classList.add("active");
    });

    var prose = document.querySelector(".docs-main .prose");
    var toc = document.getElementById("toc-list");
    var tocWrap = document.querySelector(".docs-toc");
    if (!prose || !toc) { if (tocWrap) tocWrap.style.display = "none"; return; }

    var heads = prose.querySelectorAll("h2, h3");
    heads.forEach(function (h) {
      if (!h.id) {
        h.id = h.textContent.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
      }
      var a = document.createElement("a");
      a.href = "#" + h.id;
      a.textContent = h.textContent;
      if (h.tagName === "H3") a.style.paddingLeft = "12px";
      toc.appendChild(a);
    });
    if (!toc.childElementCount && tocWrap) tocWrap.style.display = "none";
  })();
</script>"##;

pub fn render(children: &str) -> String {
    rsx! {
        <div class="docs">
            <aside class="docs-sidebar">
                { sections().iter().map(|section| rsx! {
                    <div class="group">
                        <div class="group-label">{section.name}</div>
                        { section.items.iter().map(|doc| rsx! {
                            <a href={format!("/docs/{}", doc.slug)}>{doc.title}</a>
                        }).collect::<Rsx>() }
                    </div>
                }).collect::<Rsx>() }
                <div class="group">
                    <div class="group-label">"For LLMs"</div>
                    <a href="/llms.txt">"llms.txt"</a>
                    <a href="/llms-full.txt">"llms-full.txt"</a>
                </div>
            </aside>

            <div class="docs-main">{Rsx::from_raw(children)}</div>

            <nav class="docs-toc" aria-label="On this page">
                <div class="group-label">"On this page"</div>
                <div id="toc-list"></div>
            </nav>
        </div>
        {Rsx::from_raw(TOC_SCRIPT)}
    }
    .into_html()
}
