//! Docs index, as an RSX server component: `pub async fn page` (the
//! docs/rsx-server-components.md convention — no macro, no template file).

use nextrs::rsx;
use nextrs::rsx::Rsx;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_manifest.rs"));

struct Section {
    name: &'static str,
    items: Vec<&'static DocMeta>,
}

fn sections() -> Vec<Section> {
    let mut sections: Vec<Section> = Vec::new();
    for doc in DOCS {
        match sections.last_mut() {
            Some(s) if s.name == doc.section => s.items.push(doc),
            _ => sections.push(Section {
                name: doc.section,
                items: vec![doc],
            }),
        }
    }
    sections
}

pub async fn page() -> Rsx {
    rsx! {
        <header class="prose" style="max-width:none;">
            <span class="eyebrow">"Documentation"</span>
            <h1>"nextrs docs"</h1>
            <p class="lead">
                "Everything to go from zero to a deployed Rust\u{a0}+\u{a0}React app. The same "
                "markdown that renders these pages also generates "
                <a href="/llms.txt">"llms.txt"</a>" and "<a href="/llms-full.txt">"llms-full.txt"</a>
                ", so the human docs and the LLM docs can't drift apart."
            </p>
        </header>

        { sections().iter().map(|section| rsx! {
            <section class="doc-index-section">
                <h2>{section.name}</h2>
                <div class="doc-index-grid">
                    { section.items.iter().map(|doc| rsx! {
                        <a class="card" href={format!("/docs/{}", doc.slug)}>
                            <h3>{doc.title}</h3>
                            <p>{doc.description}</p>
                        </a>
                    }).collect::<Rsx>() }
                </div>
            </section>
        }).collect::<Rsx>() }
    }
}
