use askama::Template;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_manifest.rs"));

struct Section {
    name: &'static str,
    items: Vec<&'static DocMeta>,
}

#[derive(Template)]
#[template(path = "docs/page.html")]
struct DocsIndex {
    sections: Vec<Section>,
}

fn sections() -> Vec<Section> {
    let mut sections: Vec<Section> = Vec::new();
    for doc in DOCS {
        match sections.last_mut() {
            Some(s) if s.name == doc.section => s.items.push(doc),
            _ => sections.push(Section {
                name: doc.section,
                items: vec![doc],
            }),
        }
    }
    sections
}

pub async fn render(_req: http::Request<axum::body::Body>) -> String {
    DocsIndex {
        sections: sections(),
    }
    .render()
    .unwrap()
}
