// Generated by nextrs (`nextrs realtime generate`). Do not edit — regenerate.
//
// The relay for nextrs::realtime on serverless deployments: one Durable
// Object per topic holds that topic's browser WebSockets (hibernated, so idle
// connections cost ~nothing) and its sequence counter. It has no app logic:
//
//   POST /__nx/realtime/{topic}           Authorization: Bearer $NEXTRS_REALTIME_SECRET
//        body: {"operation":"upsert"|"delete"|"invalidate","key"?,"value"?}
//        → {"sequence": n}, and a `change` frame to every subscriber
//   GET  /__nx/realtime/{topic}?token=…   WebSocket; the token is the app's signed
//        ticket: `{exp}.{hex HMAC-SHA256(secret, topic + "\n" + exp)}`
//
// The signature must match crates/nextrs/src/realtime.rs. Shared test vector:
//   HMAC-SHA256("0123456789abcdef", "todos\n1800000300")
//   = 977635521679a6b3dfe6f01fe74bcf81898c0fe67b8939ebbd9cf4671b1561ea

import { DurableObject } from "cloudflare:workers";

const PREFIX = "/__nx/realtime/";
const MAX_EVENT_BYTES = 64 * 1024;
const TOPIC = /^[A-Za-z0-9._:-]{1,128}$/;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/health") return new Response("ok");
    if (!url.pathname.startsWith(PREFIX)) return new Response("Not found", { status: 404 });
    const topic = decodeURIComponent(url.pathname.slice(PREFIX.length));
    if (!TOPIC.test(topic)) return new Response("Invalid topic", { status: 400 });
    const secret = env.NEXTRS_REALTIME_SECRET;
    if (typeof secret !== "string" || secret.length < 16) {
      return new Response("Relay misconfigured: set NEXTRS_REALTIME_SECRET", { status: 503 });
    }

    if (request.headers.get("upgrade")?.toLowerCase() === "websocket") {
      if (!(await validTicket(secret, topic, url.searchParams.get("token")))) {
        return new Response("Forbidden", { status: 403 });
      }
    } else if (request.method === "POST") {
      if (!timingSafeEqual(request.headers.get("authorization") ?? "", `Bearer ${secret}`)) {
        return new Response("Unauthorized", { status: 401 });
      }
    } else {
      return new Response("Expected a WebSocket upgrade or POST", { status: 426 });
    }
    return env.TOPICS.get(env.TOPICS.idFromName(topic)).fetch(request);
  },
};

/** One ordered meeting point per topic. */
export class Topic extends DurableObject {
  constructor(ctx, env) {
    super(ctx, env);
    this.sql = ctx.storage.sql;
    this.sql.exec(`
      CREATE TABLE IF NOT EXISTS relay_state (
        singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
        sequence INTEGER NOT NULL
      );
      INSERT OR IGNORE INTO relay_state (singleton, sequence) VALUES (1, 0);
    `);
    // Clients may keep a connection warm with a text "ping"; answered
    // without waking the object.
    ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair("ping", "pong"));
  }

  async fetch(request) {
    const topic = decodeURIComponent(new URL(request.url).pathname.slice(PREFIX.length));
    if (request.headers.get("upgrade")?.toLowerCase() === "websocket") {
      const [client, server] = Object.values(new WebSocketPair());
      this.ctx.acceptWebSocket(server);
      server.send(JSON.stringify({ type: "ready", topic, sequence: this.sequence() }));
      return new Response(null, { status: 101, webSocket: client });
    }

    const raw = await request.text();
    if (new TextEncoder().encode(raw).byteLength > MAX_EVENT_BYTES) {
      return new Response("Change too large", { status: 413 });
    }
    const change = validChange(raw);
    if (!change) return new Response("Invalid change", { status: 400 });
    const sequence = this.nextSequence();
    const frame = JSON.stringify({ type: "change", topic, sequence, ...change });
    for (const socket of this.ctx.getWebSockets()) {
      try {
        socket.send(frame);
      } catch {
        socket.close(1011, "broadcast failed");
      }
    }
    return Response.json({ sequence });
  }

  webSocketMessage(socket, message) {
    if (message !== "ping") socket.close(1008, "subscriptions are receive-only");
  }

  webSocketClose(socket, code) {
    try {
      socket.close(code === 1005 ? 1000 : code, "closing");
    } catch {}
  }

  webSocketError() {}

  sequence() {
    return Number(this.sql.exec("SELECT sequence FROM relay_state WHERE singleton = 1").one().sequence);
  }

  nextSequence() {
    return Number(
      this.sql.exec("UPDATE relay_state SET sequence = sequence + 1 WHERE singleton = 1 RETURNING sequence").one()
        .sequence,
    );
  }
}

async function validTicket(secret, topic, token) {
  if (typeof token !== "string") return false;
  const dot = token.indexOf(".");
  if (dot < 1) return false;
  const exp = Number(token.slice(0, dot));
  if (!Number.isSafeInteger(exp) || exp <= Math.floor(Date.now() / 1000)) return false;
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const mac = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(`${topic}\n${exp}`));
  const hex = [...new Uint8Array(mac)].map((b) => b.toString(16).padStart(2, "0")).join("");
  return timingSafeEqual(token.slice(dot + 1), hex);
}

function timingSafeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function validChange(raw) {
  try {
    const value = JSON.parse(raw);
    if (!value || typeof value !== "object") return null;
    if (value.operation === "invalidate") return { operation: "invalidate" };
    if (value.operation === "delete" && typeof value.key === "string") {
      return { operation: "delete", key: value.key };
    }
    if (value.operation === "upsert" && typeof value.key === "string" && "value" in value) {
      return { operation: "upsert", key: value.key, value: value.value };
    }
    return null;
  } catch {
    return null;
  }
}
