use axum::body::Body;
use http::Request;
use nextrs::conventions::MiddlewareResult;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_manifest.rs"));

/// Pages can only return 200 (they're `Request -> String`), so the unknown-slug
/// check lives here: middleware short-circuits with a real 404 status before
/// any rendering starts. The response bypasses layout composition, so the body
/// is a small self-contained document.
pub async fn handle(req: Request<Body>) -> MiddlewareResult {
    let slug = req.uri().path().rsplit('/').next().unwrap_or("");
    if DOCS.iter().any(|d| d.slug == slug) {
        MiddlewareResult::next(req)
    } else {
        MiddlewareResult::response((
            http::StatusCode::NOT_FOUND,
            axum::response::Html(NOT_FOUND_HTML),
        ))
    }
}

const NOT_FOUND_HTML: &str = r#"<!doctype html>
<html lang="en" data-theme="dim">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Not found · nextrs</title>
  <link rel="stylesheet" href="/style.css?v=20260630">
</head>
<body class="min-h-screen flex items-center justify-center">
  <div class="text-center space-y-4">
    <h1 class="text-4xl font-bold">404</h1>
    <p class="text-base-content/70">No doc with that name.</p>
    <a href="/docs" class="btn btn-sm">Back to docs</a>
  </div>
</body>
</html>
"#;
