//! One rendered doc article, as an RSX server component. The old version
//! extracted the slug from raw request parts and format!-ed an HTML string;
//! the RSX convention is a full Axum handler, so `Path` extraction and
//! escaping-by-default come for free (`doc.html` is the one deliberate
//! `from_raw`: it's our own build-time-rendered markdown).

use axum::extract::Path;
use nextrs::rsx;
use nextrs::rsx::Rsx;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
// Defines `Doc` and `DOCS` — manifest fields plus the pre-rendered HTML.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_content.rs"));

pub async fn page(Path(slug): Path<String>) -> Rsx {
    // Unknown slugs are 404'd by this segment's middleware before we run.
    let Some(doc) = DOCS.iter().find(|d| d.slug == slug) else {
        return rsx! { <h1>"Not found"</h1> };
    };

    rsx! {
        <article class="prose">
            <h1>{doc.title}</h1>
            <p class="lead">{doc.description}</p>
            {Rsx::from_raw(doc.html)}
        </article>
    }
}
