use axum::RequestPartsExt;
use axum::extract::Path;

// Generated by nextrs::docs::emit_docs (see build.rs) from content/docs/*.md.
// Defines `Doc` and `DOCS` — manifest fields plus the pre-rendered HTML.
include!(concat!(env!("OUT_DIR"), "/nextrs_docs_content.rs"));

pub async fn render(req: http::Request<axum::body::Body>) -> String {
    let (mut parts, _body) = req.into_parts();
    let slug = match parts.extract::<Path<String>>().await {
        Ok(Path(slug)) => slug,
        Err(_) => String::new(),
    };

    // Unknown slugs are 404'd by this segment's middleware before we run.
    let Some(doc) = DOCS.iter().find(|d| d.slug == slug) else {
        return "<h1>Not found</h1>".to_string();
    };

    format!(
        concat!(
            "<article class=\"prose max-w-3xl\">",
            "<h1>{title}</h1>",
            "<p class=\"lead\">{description}</p>",
            "{html}",
            "</article>",
        ),
        title = doc.title,
        description = doc.description,
        html = doc.html,
    )
}
