// Regenerate src/generated/index.ts after orval runs, so every generated
// tag module is exported automatically — a hand-maintained re-export list
// always goes stale as endpoints are added.
import { readdirSync, writeFileSync } from "node:fs";

const dir = new URL("../src/generated/", import.meta.url);
const tags = readdirSync(dir, { withFileTypes: true })
  .filter((e) => e.isDirectory() && e.name !== "model")
  .map((e) => e.name)
  .sort();

const lines = [
  "// @generated by scripts/gen-barrel.mjs (npm run gen). Do not edit.",
  ...tags.map((t) => `export * from "./${t}/${t}";`),
  'export * from "./model";',
];
writeFileSync(new URL("index.ts", dir), lines.join("\n") + "\n");
console.log(`gen-barrel: exported ${tags.length} module(s) + model`);
