// GET /llms-full.txt — full markdown text of every doc, generated by the docs
// build step (nextrs::docs::emit_docs in build.rs). Embedded at compile time.
pub async fn get(_req: http::Request<axum::body::Body>) -> impl axum::response::IntoResponse {
    (
        [("content-type", "text/plain; charset=utf-8")],
        include_str!(concat!(env!("OUT_DIR"), "/llms-full.txt")),
    )
}
