// GET /llms.txt — the llmstxt.org-style index generated by the docs build
// step (nextrs::docs::emit_docs in build.rs) from the same markdown sources
// that render /docs, so the two can't drift. Embedded at compile time.
pub async fn get(_req: http::Request<axum::body::Body>) -> impl axum::response::IntoResponse {
    (
        [("content-type", "text/plain; charset=utf-8")],
        include_str!(concat!(env!("OUT_DIR"), "/llms.txt")),
    )
}
