// Vercel deployment entry point. Mirrors example/src/main.rs but uses
// vercel_runtime::run instead of axum::serve. This file will be generated by
// codegen once Phase 1 lands; it's hand-wired for now so we can deploy and
// measure before doing the codegen work.
//
// Note on `StreamingVercelService`: vercel_runtime's `VercelLayer` only treats
// a response as streaming when its content-type is `text/event-stream` or
// `application/json` (see `vercel_runtime::axum::StreamingUtils::is_streaming_response`).
// Our framework streams `text/html`, so VercelLayer would buffer the whole
// response. The service below has the same request-side conversion as
// VercelService but unconditionally streams the response body.

use std::convert::Infallible;
use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll};

use axum::body::Body as AxumBody;
use axum::http::Request as AxumRequest;
use axum::response::Response as AxumResponse;
use http_body_util::BodyExt;
use tower::{Layer, Service, ServiceBuilder, ServiceExt};
use vercel_runtime::axum::StreamingUtils;
use vercel_runtime::{AppState, Error as VercelError, Request as VercelRequest, ResponseBody};

use nextrs::conventions::{RouteEntry, RouteRegistry};
use nextrs::router::build_router;

#[path = "../example/app/layout.rs"]
mod root_layout;
#[path = "../example/app/page.rs"]
mod root_page;

#[path = "../example/app/simple/page.rs"]
mod simple_page;

#[path = "../example/app/with-loading/page.rs"]
mod with_loading_page;
#[path = "../example/app/with-loading/loading.rs"]
mod with_loading_loading;

#[path = "../example/app/with-layout/layout.rs"]
mod with_layout_layout;
#[path = "../example/app/with-layout/page.rs"]
mod with_layout_page;
#[path = "../example/app/with-layout/loading.rs"]
mod with_layout_loading;

#[tokio::main]
async fn main() -> Result<(), VercelError> {
    let mut registry = RouteRegistry::new();

    registry.add(RouteEntry {
        path: "/".to_string(),
        page: Some(Box::new(|req| Box::pin(root_page::render(req)))),
        layout: Some(Box::new(root_layout::render)),
        loading: None,
        methods: vec![],
    });

    registry.add(RouteEntry {
        path: "/simple".to_string(),
        page: Some(Box::new(|req| Box::pin(simple_page::render(req)))),
        layout: None,
        loading: None,
        methods: vec![],
    });

    registry.add(RouteEntry {
        path: "/with-loading".to_string(),
        page: Some(Box::new(|req| Box::pin(with_loading_page::render(req)))),
        layout: None,
        loading: Some(Box::new(with_loading_loading::render)),
        methods: vec![],
    });

    registry.add(RouteEntry {
        path: "/with-layout".to_string(),
        page: Some(Box::new(|req| Box::pin(with_layout_page::render(req)))),
        layout: Some(Box::new(with_layout_layout::render)),
        loading: Some(Box::new(with_layout_loading::render)),
        methods: vec![],
    });

    let router = build_router(registry);
    let app = ServiceBuilder::new()
        .layer(StreamingVercelLayer)
        .service(router);

    vercel_runtime::run(app).await
}

#[derive(Clone)]
struct StreamingVercelLayer;

impl<S> Layer<S> for StreamingVercelLayer {
    type Service = StreamingVercelService<S>;
    fn layer(&self, inner: S) -> Self::Service {
        StreamingVercelService { inner }
    }
}

#[derive(Clone)]
struct StreamingVercelService<S> {
    inner: S,
}

impl<S> Service<(AppState, VercelRequest)> for StreamingVercelService<S>
where
    S: Service<AxumRequest<AxumBody>, Response = AxumResponse<AxumBody>, Error = Infallible>
        + Send
        + Clone
        + 'static,
    S::Future: Send + 'static,
{
    type Response = hyper::Response<ResponseBody>;
    type Error = VercelError;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        match self.inner.poll_ready(cx) {
            Poll::Ready(Ok(())) => Poll::Ready(Ok(())),
            Poll::Ready(Err(_)) => Poll::Ready(Err("Inner service error".into())),
            Poll::Pending => Poll::Pending,
        }
    }

    fn call(&mut self, (_state, req): (AppState, VercelRequest)) -> Self::Future {
        let mut service = self.inner.clone();
        Box::pin(async move {
            // Vercel Request -> axum Request (collect body into bytes; same
            // shape as the upstream VercelService — request bodies are small).
            let (parts, body) = req.into_parts();
            let body_bytes = BodyExt::collect(body)
                .await
                .map_err(|e| Box::new(e) as VercelError)?
                .to_bytes();
            let axum_req = AxumRequest::from_parts(parts, AxumBody::from(body_bytes));

            // Run the axum router.
            let ready = ServiceExt::ready(&mut service)
                .await
                .map_err(|_| "Service not ready")?;
            let axum_resp = Service::call(ready, axum_req)
                .await
                .map_err(|_| "Service error")?;

            // Force streaming for ALL responses (this is the only difference
            // from VercelService — we don't gate on content-type).
            let (resp_parts, resp_body) = axum_resp.into_parts();
            let stream_body = StreamingUtils::create_stream_body(resp_body).await?;
            Ok(hyper::Response::from_parts(resp_parts, stream_body))
        })
    }
}
